services:
  mongo:
    image: mongo:6
    container_name: birthday-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: birthday-app
    restart: always
    ports:
      - "5000:5000"
    environment:
       MONGODB_URI: mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@birthdayservice.gfe3aok.mongodb.net/birthday_service?retryWrites=true&w=majority&appName=BirthdayService
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongo_data:
